KAN-67: Opleiding Controller
JorenTengrootenhuysen/ZiekenFonds.API pull request #24
Opened 2024-12-03 13:33 UTC by WardGijsels

OpleidingController aangemaakt met bijhorende dto's en functies in de repository en interface.

**Jira Link**: https://r0994450.atlassian.net/browse/KAN-64?atlOrigin=eyJpIjoiYjQ0YjVjNDcwYzQ0NDg5YWE1MjkzNGRmODc5ZmFmYjciLCJwIjoiaiJ9

2024-12-03 13:47 UTC, RensTgh approved these changes
ik vind goeie

2024-12-05 12:34 UTC, r0841547 requested changes
mapping aanpassen

2024-12-05 12:34 UTC, r0841547 commented on Configuration/MapperProfile.cs
> +            CreateMap<CreateOpleidingDto, Opleiding>()
2 keer dezelfde mapper aangemaakt voor create opleiding dto

2024-12-05 16:19 UTC, WardGijsels commented
> mapping aanpassen

Beide mappings zijn nodig omdat ze verschillende doelen hebben:

- De eerste mapping zet specifieke velden om, zoals VereisteOpleidingIds naar VereisteOpleidingen.
- De tweede mapping zorgt voor algemene conversie tussen Opleiding en CreateOpleidingDto in beide richtingen.

2024-12-06 13:12 UTC, JorenTengrootenhuysen approved these changes

2024-12-06 13:12 UTC, merged